
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    schemas:
      - public
      - list
    baseline-on-migrate: true
    driver-class-name: org.postgresql.Driver

server:
  port: 8081

logging:
  level:
    sql: info
jwt:
  secret: lg3h3w4erh5g1reg0ih3891fdhv3bfihvifdhsv45fhidvfiwehfi7weg8wh